apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mejk9o1qi-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mejk9o1qi-python 
  name: mejk9o1qi-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: mejk9o1qi-python 
